eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      edge: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:eureka}:${EUREKA_SERVER_PORT:8761}/eureka/

logging:
  level:
    # 调测选项
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

swan:
  upload-folder: ${UPLOAD-FOLDER:/swan/appendix}