server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  datasource:
    platform: h2
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
