spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
          includeExpression: metadata['edge'] == 'true'
      routes:
        - id: appendix
          uri: lb://appendix
          predicates:
            - Path=/appendix/**
          filters:
            - StripPrefix=0
        - id: oauth
          uri: lb://auth
          predicates:
            - Path=/oauth/**
          filters:
            - StripPrefix=0
        - id: demo
          uri: lb://demo
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      edge: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:eureka}:${EUREKA_SERVER_PORT:8761}/eureka/