### get token
POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded

client_id=admin&client_secret=admin&grant_type=password&username=2&password=123456

> {%
client.global.set('access_token', response.body.access_token);
client.global.set('refresh_token', response.body.refresh_token);
%}

### add
POST http://localhost:9091/demo
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "name"
}

### page
GET http://localhost:9091/demo?rows=10

### getById
GET http://localhost:9091/demo/1
Authorization: Bearer {{access_token}}

### update
PUT http://localhost:9091/demo/1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "name-update"
}

### delete
DELETE http://localhost:9091/demo/1
Authorization: Bearer {{access_token}}
