FROM openjdk:8-jre-slim-buster

ENV TZ "Asia/Shanghai"

COPY /swan-appendix-app/build/libs/swan-appendix-app-1.0.0.SNAPSHOT.jar /swan/app.jar

WORKDIR /swan

ENTRYPOINT ["java","-jar","/swan/app.jar"]