name: Release CI

env:
  PUSH_IMAGE: ${{ github.event_name == 'release' }}
  RELEASED_NAME: ${{ github.event.release.name }}

on:
  release:
    types:
      - released
      - prereleased

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push eureka
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ env.PUSH_IMAGE }}
          file: deployment/Dockerfile-eureka
          tags: |
            myifeng/swan-eureka:latest
            myifeng/swan-eureka:${{ env.RELEASED_NAME }}
          platforms: linux/amd64,linux/arm64
      - name: Build and push appendix
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ env.PUSH_IMAGE }}
          file: deployment/Dockerfile-appendix
          tags: |
            myifeng/swan-appendix:latest
            myifeng/swan-appendix:${{ env.RELEASED_NAME }}
          platforms: linux/amd64,linux/arm64
      - name: Build and push auth
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ env.PUSH_IMAGE }}
          file: deployment/Dockerfile-auth
          tags: |
            myifeng/swan-auth:latest
            myifeng/swan-auth:${{ env.RELEASED_NAME }}
          platforms: linux/amd64,linux/arm64
      - name: Build and push config
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ env.PUSH_IMAGE }}
          file: deployment/Dockerfile-config
          tags: |
            myifeng/swan-config:latest
            myifeng/swan-config:${{ env.RELEASED_NAME }}
          platforms: linux/amd64,linux/arm64
      - name: Build and push gateway
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ env.PUSH_IMAGE }}
          file: deployment/Dockerfile-gateway
          tags: |
            myifeng/swan-gateway:latest
            myifeng/swan-gateway:${{ env.RELEASED_NAME }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push demo
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ env.PUSH_IMAGE }}
          file: deployment/Dockerfile-demo
          tags: |
            myifeng/swan-demo:latest
            myifeng/swan-demo:${{ env.RELEASED_NAME }}
          platforms: linux/amd64,linux/arm64
